repository:
  name: node-ahmad
  description: npm package with meta data about me!
  topics: meta, about
  homepage: https://www.ahmadnassri.com
  private: false
  has_issues: false
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
